### ISSUE TITLE
question

### ISSUE THREAD

**Issue by RenRunyesh** [chamwen/NT-Benchmark#1]
Can you explain the details of the SEED data set in your paper? Or can we share the.npz packet.Thanks!

**Comment by chamwen** [comment]
Hi, thx for your interest to this survey. In Section 5.3.1 of our paper, we have explained it:

SEED is an electroencephalogram (EEG) based emotion recognition dataset, which contains 15 healthy subjects, each recorded with positive, neutral and negative emotions stimulated by video clips. Only the first three subjects, each with 3394 samples, were selected to construct a subset. We used the 310 pre-computed differential entropy features, extracted from different EEG channels in five frequency bands.

The details of the SEED dataset is in [SEED Dataset](https://bcmi.sjtu.edu.cn/~seed/seed.html). If you want the npz file, you can email me with wenz@hust.edu.cn
